clc;clear all
fun1 = @(x)min((x(1)^2 + x(2) - 11)^2 + (x(1) + x(2)^2 + 7)^2);

x0 = [0,0];
[x_search,fval_search] = fminsearch(fun1,x0);
[x_unc,fval_unc] = fminunc(fun1,x0);
fprintf('fminsearch meathod: \nx = (%3.8f,%3.8f), \ny = %3.8f\n\n',...
    x_search(1),...
    x_search(2),...
    fval_search);
fprintf('fminunc method: \nx = (%3.8f,%3.8f), \ny = %3.8f\n',...
    x_unc(1),...
    x_unc(2),...
    fval_unc);