clc

fun4 = @(x)min(100 * ((x(3) - 10 * Theta(x(1),x(2)))^2 ...
    + ((x(1)^2 + x(2)^2)^(1/2) - 1)^2) + x(3)^2);

x0 = [10,10,10];
[x_search,fval_search] = fminsearch(fun4,x0);
[x_unc,fval_unc] = fminunc(fun4,x0);
fprintf('fminsearch method: \nx = (%3.8f,%3.8f,%3.8f), \ny = %3.8f\n\n',...
    x_search(1),...
    x_search(2),...
    x_search(3),...
    fval_search);
fprintf('fminunc method: \nx = (%3.8f,%3.8f,%3.8f), \ny = %3.8f\n',...
    x_unc(1),...
    x_unc(2),...
    x_unc(3),...
    fval_unc);

%- Definition of function Theta -%
function y = Theta(a,b)
    if a > 0
        y = 1 / (2 * pi) * atan(a ./ b);
    else
        y = 1 / (2 * pi) * atan(a ./ b) + 1 / 2;
    end
end